### ISSUE TITLE
Is this plugin still in development?

### ISSUE THREAD

**Issue by max1mvs** [marcosvidal/Sketch-Notebook#100]
Seems to me that the latest update was in November last year. Tried to contact Marcos regarding updates with no avail. Issues are posted, but no words from him. Is this plugin still in development or should we look for alternatives?

**Comment by max1mvs** [comment]
Well. The last version was from November 2016 (Paid version), and there seems to be some issues with it. But no words from the developer. Not by mail either…

**Comment by marcosvidal** [comment]
Yes, it's still in development. Feel free to drop me a line if you have any feedback.
