### ISSUE TITLE
Notebook Pro not working in sketch 45 - (FIXED)

### ISSUE THREAD

**Issue by markdodgson** [marcosvidal/Sketch-Notebook#101]
I would love to know if there will be an update. The plugin is not working at all in Sketch v45. I really love this plugin but I need to find a solution that's going to be in active development.

**Comment by dusskapark** [comment]
Same issues I cannot manage my existing comments...

**Comment by jabarnett** [comment]
Check your email. I had the same problem when I went to start annotating today... but found an email with a link to download the update. And now it seems to be working.

**Comment by markdodgson** [comment]
Thanks @jabarnett. Did the email get sent today? I haven't seen anything :(

**Comment by markdodgson** [comment]
Thank you @marcosvidal. Loving the new version of Notebook. I repurchased with the premium service. Please keep developing this plugin. It's really really useful :)

**Comment by marcosvidal** [comment]
Thanks for your nice words mark! I really appreciate it.

Feel free to give me any feedback on the plugin :)

Cheers,
Marcos.

**Comment by dragonflyATL** [comment]
Hi Maros
I just downloaded Notebook Pro, and can't get it to work in Sketch v. 45.2, what is the fix for this?

Thanks
T.

**Comment by Plumosplumos** [comment]
Some problem..notebook is not working with sketch 45.2 :(

**Comment by markdodgson** [comment]
Hi Marcos, I hope things are going well. I was just wondering if there’s an update coming for Notebook Pro. I’m running Sketch 46.2 and Notebook Pro is unusable. It doesn’t load the comments at all.

Let me know what you think
Mark

--
Mark Dodgson
UX/UI & Visual Designer

150 Morwick Drive
Ancaster, Ontario 
L9G 4Z5

P: +1 (905) 308-4397
E: info@markdodgson.com <mailto:info@markdodgson.com>
W: markdodgson.com <http://markdodgson.com/>
T: @markdodgson <https://twitter.com/markdodgson>

**Comment by jvollands** [comment]
I recently purchased the NotebookPro version to trial but on the very same day I found that in Sketch version 47.1 when you have 5 or more comments enabled you are unable to edit the 5th comment and Sketch crashes.

Is this something you can help resolve please as I feel this is such a useful plugin to have but unable to complete my work given this limitation. 

Thanks,
Jamie

**Comment by marcosvidal** [comment]
@jvollands Yes, this was fixed with the release of notebook 1.462. Check your inbox for the update and if you don't find it, just write me to the plugin support address and I'll help you upgrade :)
