### ISSUE TITLE
Feature request: Size & position of comment indicators

### ISSUE THREAD

**Issue by patowod** [marcosvidal/Sketch-Notebook#102]
Hi Marcos,

the new release is great. We just tested it and really like it. We are heavily relying on Invision and Confluence and therefore explored the possibilities regarding a few features and would really find following helpful regarding the comment indicators:

1. Customize the indicator size (if an image gets downscaled for some reason, e.g. confluence) so it is still readable.

2. Position of indicators sometimes overlay the selected layer. It would be awesome if this could be adjustable, e.g Indicator is placed based on top-left layer corner with a certain offset. Current workaround for us is a bg layer that is then commented. Which of course is not ideal.

What do you think? 
Best regards, 
Patrick

**Comment by marcosvidal** [comment]
Please keep in mind that updates on the plugin are sent over email after you download it from http://marcosvid.al/sketch-notebook

This repository is kept only with historical purposes, not as a source of updates or a feedback channel.

You can also contact me at support@marcovid.al if you need further information.
