### ISSUE TITLE
Feature request: Export of Artboard with indicators and comments separately

### ISSUE THREAD

**Issue by patowod** [marcosvidal/Sketch-Notebook#103]
Hi,

for use with Invision and client communication, as well as documentation it would be great if you could consider the possibility to display the artboard only with overlayed indicators (so this can be exported) as well as an export of only the comments sidebar itself.

In addition (and I don’t now how far fetched this is) do you think it is possible to export the comments with indicator as a plain textfile? Basically this would make you our hero.

Best regards. Looking forward to hearing from you.

**Comment by marcosvidal** [comment]
Thanks for the feedback!

Please keep in mind that updates on the plugin are sent over email after you download it from http://marcosvid.al/sketch-notebook

This repository is kept only with historical purposes, not as a source of updates or a feedback channel.

You can also contact me at support@marcovid.al if you need further information.
