### ISSUE TITLE
Feature request: Toggle if artboards are moved when showing comment sidebar

### ISSUE THREAD

**Issue by patowod** [marcosvidal/Sketch-Notebook#104]
Hi Marcos, 

a fellow designer just pointed out something else: a toggle to switch on or off the behavior that artboards are moved, when showing the comment sidebar would be really nice. 

Background: When working with multiple artboards it can be disturbing, so if there would be enough space it would be nice if the other artboards (on the right hand of the current one) would not be moved but stayed in place.

Best regards.

**Comment by marcosvidal** [comment]
Thanks for the feedback!

Please keep in mind that updates on the plugin are sent over email after you download it from http://marcosvid.al/sketch-notebook

This repository is kept only with historical purposes, not as a source of updates or a feedback channel.

You can also contact me at support@marcovid.al if you need further information.
