### ISSUE TITLE
Add security to your website

### ISSUE THREAD

**Issue by hellais** [marcosvidal/Sketch-Notebook#105]
This plugin seems to do what I need. I would like to buy it, but your website is not in HTTPS and it's asking for my credit card information and transmitting it in plaintext.

If you are requesting people to enter credit card information, you should have your site support HTTPS. Seriously there is no reason not do to so in this day and age, where you can even get free SSL certificates from something like https://letsencrypt.org/.

Edit: it seems like your site is actually loading a form from this site: https://app.simplegoods.co/i/DTAKBHXV. If you don't want to add SSL to your site, then at the bare minimum redirect them to that site when they are about to make the purchase.

**Comment by marcosvidal** [comment]
Thanks for your feedback @hellais The connection to the purchase process was always with https conections. And now the whole site uses it as well.
