### ISSUE TITLE
Pop up for notes isn't working

### ISSUE THREAD

**Issue by Kymberlee** [marcosvidal/Sketch-Notebook#106]
Hoping someone can help.

I can't get the “Add note” option to open a modal window to add the notes. It’s adding the “nb—sidebar” layer but nothing else. The layer cannot be edited within the file (can’t add the title, notes, etc).
 
Running a Mac v 10.11.3 OSX El Capitan and Sketch v 43.2. I have both automatically installed the NB plug in, as well as manually and neither results in the modal to add comments.
 
Any help would be greatly appreciated.

**Comment by tylerlee** [comment]
Same (first time using app, so may be doing something wrong?) but I think this is malfunctioning.

**Comment by mijlee** [comment]
Yep I am also having this problem as well. Using Sketch 46. I used the free version in the past but have now bought the pro version so very frustrating that it doesn’t work.

**Comment by thgrill** [comment]
Same here ... wanted to try your plugin in order to verify if it works for my sketch documentation process ... :( Thought about buying it if it works ...

Using Sketch 46.1

**Comment by thetwosents** [comment]
👍 I was literally so excited to use this

**Comment by myersmc16** [comment]
I just downloaded the plugin and am running into the same issue on Sketch 46.2

**Comment by jvollands** [comment]
I'm having the same problem. The same day I bought the pro version the plugin did not work - this is very frustrating. I've tried contacting Marcos a number of times now but no reply.

I'm running Sketch 47 and found I can add as many comments as I like but when I come to edit the 5th comment and more it crashes Sketch. Is anyone else seeing this?

Marcos are you able to provide an update please as its such a good plugin but not usable at the moment

**Comment by marcosvidal** [comment]
### The latest version of the notebook plugin (1.462) works totally fine with sketch 46 & 47.

With every sketch update that makes the plugin to stop working I always release a fix and send an email to every user with the download link. If at anytime something stops working, just check your inbox (the one you used to download the plugin). 

Also make sure that you don't have any filter blocking my emails and that they're not sent directly to the spam folder or trash bin.

In any case, if any user of the plugin has a problem with it, please use the support email address listed in my site and I will personally help you to solve your problems. 

I'd like to keep the github project for more technical-related issues.

Thanks for your understanding.

Marcos.
