### ISSUE TITLE
Sketch App Shutdown

### ISSUE THREAD

**Issue by Adawson718** [marcosvidal/Sketch-Notebook#108]
I'm using Sketch App 48 and now when I add a comment to my project with the notebook plugin the entire application shuts down. This issues just started today after the Sketch app update.

**Comment by staciesheldon** [comment]
Same here and I just purchased it on Monday and was about to use it for the very first time. :-P

**Comment by Adawson718** [comment]
@marcosvidal When will there be a fix for this. I'm in the middle of a project and this is holding me back.

**Comment by marcosvidal** [comment]
You should receive an email with the update within the next hours. 

@Adawson718 if you are in hurry just mail me to the support address and I'll send you a copy of the updated plugin :)

**Comment by Adawson718** [comment]
@marcosvidal What is the support address? I don't think I have that.

**Comment by marcosvidal** [comment]
You can find it in the plugin's page: https://marcosvid.al/sketch-notebook

**Comment by staciesheldon** [comment]
I just installed the new version of Notebook but perhaps because I have Sketch 48.1 now as soon as I changed the color option to Sepia it shut Sketch down immediately. Tried it twice. :-(

**Comment by marcosvidal** [comment]
@staciesheldon You should have an email with an update for that. If not, write me an email to the support address
