### ISSUE TITLE
How can I change the width of the sidebar?

### ISSUE THREAD

**Issue by studiotemple** [marcosvidal/Sketch-Notebook#111]
default sidebar width : 500px

i want sidebar width : 350px

**Comment by marcosvidal** [comment]
Please keep in mind that updates on the plugin are sent over email after you download it from http://marcosvid.al/sketch-notebook

This repository is kept only with historical purposes, not as a source of updates or a feedback channel.

You can also contact me at support@marcovid.al if you need further information.
