### ISSUE TITLE
How can I update metadata only once?

### ISSUE THREAD

**Issue by aurelioarantes** [marcosvidal/Sketch-Notebook#112]
I tried to update as Symbol, but every time I update metadata goes back to first information. 
It means the author must the company's name that I am working for, not my name. The project's name must something that I have chosen, not the file's name. 

I have multiples artboards and multiples pages as well. I'm working with Sketch 49.
How can I do that?

**Comment by marcosvidal** [comment]
Please keep in mind that updates on the plugin are sent over email after you download it from http://marcosvid.al/sketch-notebook

This repository is kept only with historical purposes, not as a source of updates or a feedback channel.

You can also contact me at support@marcovid.al if you need further information.
