### ISSUE TITLE
Can't create notes

### ISSUE THREAD

**Issue by mzoukas** [marcosvidal/Sketch-Notebook#113]
Just purchased Notebook Pro and I cant create notes. 
I am using Sketch 50 with High Sierra 10.13.4. 

Here's what's happening. 
When working in a new document, after selecting a layer and clicking new note (or using key command) I am taken to a new page titled --nb--assets with a black square and no artboard. 
I do not get a pop up that asks what I want to write in the note. 

If I go back to my original page and try it again, a new layer called --nb--sidebar gets created. I am unable to see the sidebar on my artboard regardless of me clicking on the view/hide icon on the layer. If I click on the "hide icon" in the notebook toolbar, then half of my artboard disappears. 
If I try to create another new note after that point, nothing happens whatsoever. 

I have uninstalled and reinstalled the plugin to see if that would fix anything but it has not.

**Comment by nathanmaguire** [comment]
I'm having the exact same issues. I have Notebook Pro plugin installed, upgraded to Sketch 50 and am seeing the same issue above. I've been unable to find a workaround and unable to use the plugin currently.

**Comment by lukeaikman** [comment]
Same issue as above.

**Comment by mprelich** [comment]
Same issue here

**Comment by leanminmachine** [comment]
Haven't purchased Notebook Pro, but am using the plugin I got via Sketchpacks. 
Same issue here! 

I'm on:
- Sketch Version 50
- Mac OS 10.13.4

**Comment by BanshaTang** [comment]
Same issue here, Sketch version 50.2, plugin version 1.481

**Comment by clandiva** [comment]
Same here. 

Sketch v. 50.2, Plugin downloaded yesterday.

**Comment by lukeaikman** [comment]
@leanminmachine pro version also doesn't work

**Comment by ipatschneider** [comment]
Same issue here - Sketch Version 50.2

**Comment by Noah00001** [comment]
Same issue here on Notebook Pro - Sketch version 50.2, Plugin version 1.481

**Comment by JNTHNDSZ** [comment]
Same issue Sketch v50.2 Plugin v1.5

**Comment by mxmcsc** [comment]
Yup. Same issue here. Working sometimes and other times it doesn't do anything as per the above. On occasion it stretches the whole artboard across. Very buggy right now

**Comment by BanshaTang** [comment]
@mxmcsc If it stretches the whole artboard across, please check if you enable "Adjust content on resize" of the artboard.

**Comment by mxmcsc** [comment]
Amazing. Yes. That worked. So strange that it's doing it on some and not
others.
Still having big issues though. Often nothing happens.

**Comment by dusskapark** [comment]
Same issue in Sketch 51, Notebook pro

**Comment by pdkaizer** [comment]
Same issue in Sketch 51, Notebook pro

**Comment by JunsuKim** [comment]
Same issue in Sketch 51.2, Notebook pro

**Comment by chelsey-wiley** [comment]
Same issue in Sketch 51.2, Notebook pro 
@marcosvidal Do you have any solutons?

**Comment by JunsuKim** [comment]
Same issue in Sketch 51.3, Notebook pro... 
plz fix it!

**Comment by marcosvidal** [comment]
Guys, I just published the update.

Please keep in mind that updates on the plugin are sent over email after you download it from http://marcosvid.al/sketch-notebook

This repository is keept only with a historic purpose, not as a source of updates or a feedback channel.

You can also contact me at support@marcovid.al if need further information.
