### ISSUE TITLE
Ability to support new lines in the comment section

### ISSUE THREAD

**Issue by JolandaNava** [marcosvidal/Sketch-Notebook#114]
There is currently no way to format the input comment. Does the plugin currently support this feature?

#### What I'm after
I would like to have the ability to format some basic paragraphs etc to help make larger comment blocks more readable. My goal is to annotate pages with API requests and response JSON examples. Support for monospaced fonts inside backtick blocks would also be a welcome addition.

#### Why me/others might want this:
This will help create a more functional design documentation that the developers, backend engineers and designers can all collaborate using. Just a simple newlines alone will go a long way in making longer comments more readable.

**Comment by marcosvidal** [comment]
This is really interesting! Thanks for the feedback.

Please keep in mind that updates on the plugin are sent over email after you download it from http://marcosvid.al/sketch-notebook

This repository is kept only with historical purposes, not as a source of updates or a feedback channel.

You can also contact me at support@marcovid.al if you need further information.
