### ISSUE TITLE
Markdown support

### ISSUE THREAD

**Issue by thgrill** [marcosvidal/Sketch-Notebook#115]
Please implement Markdown support in the comment section. This would absolutely improve the usefulness of the plugin

**Comment by marcosvidal** [comment]
This is really interesting, I will keep it in mind for future releases.

Please keep in mind that updates on the plugin are sent over email after you download it from http://marcosvid.al/sketch-notebook

This repository is kept only with historical purposes, not as a source of updates or a feedback channel.

You can also contact me at support@marcovid.al if you need further information.
