### ISSUE TITLE
Disable meta information

### ISSUE THREAD

**Issue by asaadmahmood** [marcosvidal/Sketch-Notebook#116]
Is there a way to disable the meta information inside the sidebar. I don't find that information useful and I think it takes away space from the comments section.

**Comment by marcosvidal** [comment]
Yes, you can remove it and use the command "update comments". 

Please keep in mind that updates on the plugin are sent over email after you download it from http://marcosvid.al/sketch-notebook

This repository is kept only with historical purposes, not as a source of updates or a feedback channel.

You can also contact me at support@marcovid.al if you need further information.
