### ISSUE TITLE
Not compatible or working with Sketch v52

### ISSUE THREAD

**Issue by jboris18** [marcosvidal/Sketch-Notebook#117]
The plugin is not working correctly in the latest version of Sketch. When I try to use it, it creates the NB Assets in the wrong location and the screen goes completely white.  Help!  It appears to be creating an the nb assets folder on a new empty page.

**Comment by chelsey-wiley** [comment]
I am having the same issue @marcosvidal will you be issuing an update anytime soon?

**Comment by darren-james** [comment]
I'm having the same problem exactly. I also notice that nothing has occurred on this repository for a very long time and not issues have been resolved. Does that mean there is no active development or maintenance, and thus the money I spent on Premium (and the updates that come with that) was a pointless expense if it is not being maintained?? That would be a shame as the ability to add and manage annotations was a key feature that made me switch from Omnigraffle (where I could have everything, but not collaborate with others who only had Sketch) to Sketch.

**Comment by jboris18** [comment]
I emailed Marcos the developer, and he said he was working on an update. Hopefully it gets here soon!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by darren-james** [comment]
That's good news. Wow, wasn't expecting that from the history recorded here on the repo. Ok.

**Comment by marcosvidal** [comment]
Guys, I just published the update.

Please keep in mind that updates on the plugin are sent over email after you download it from http://marcosvid.al/sketch-notebook

This repository is keept only with a historic purpose, not as a source of updates or a feedback channel.

You can also contact me at support@marcovid.al if need further information.

**Comment by Morgann7** [comment]
Hi @marcosvidal.  Is it possible that I can get this update also, please?  I'm currently running version 1.5 of the plugin on Sketch 52.3 but it keeps crashing.  I'm assuming it's the same issue. 

Thanks, Morgan

**Comment by asaadmahmood** [comment]
@marcosvidal I emailed you my invoice at support@marcovid.al, I haven't received the update.
Can you please send it to me too.

**Comment by skimav86** [comment]
Hi, 
@marcosvidal I have paid for the plugin online, but have not received a download link. Does anyone have thoughts on how to get the latest sketch plugin?

**Comment by skimav86** [comment]
I am using sketch v52.6
