### ISSUE TITLE
Plugin stopped working in Sketch 53.2 (72643）

### ISSUE THREAD

**Issue by zifeixu85** [marcosvidal/Sketch-Notebook#119]
I'm currently running version 1.51 of the plugin on Sketch 53.2 but it keeps crashing.

**Comment by ZTfer** [comment]
not work in 53.2

**Comment by marcosvidal** [comment]
The last two numbers of the plugin version is a reference to the sketch version that is compatible with. So, Notebook 1.51 works fine with sketch 51.

To use the plugin with sketch 53 or 54 you'll need Notebook 1.53. To download it, use the link included in the email update that you should have received.

Also, please note that I'm willing to help, but this repository is not the place to do it. There is a support mail which you can use to get a quicker answer.
