### ISSUE TITLE
Can't easily scan document

### ISSUE THREAD

**Issue by joshuamauldin** [marcosvidal/Sketch-Notebook#12]
The number's color scheme seems to blend into the canvas' design so much that it's difficult to find the numbers.

Have you considered something more unlikely to be used in a design like a magenta or cyan? I'm happy to help test this out with you if you'd like.

**Comment by marcosvidal** [comment]
The original version had white borders around every dot to avoid that effect. I've missed that at some point. It'll be the default style on th enext release. 

Thanks for pointing this out @joshuamauldin !!

**Comment by joshuamauldin** [comment]
My pleasure, señor.
