### ISSUE TITLE
Plugin doesn't work on sketch 52.6

### ISSUE THREAD

**Issue by alengton** [marcosvidal/Sketch-Notebook#122]
I just bought notebook2 and while it loads on sketch fine, it doesn't work at all. I tried contacting support twice on two different emails (info@owl.tools and support@marcovid.al) but neither are working. 

Order number: FotWYpiuStE39V

Can you help please? Thank you.

**Comment by marcosvidal** [comment]
Hello Alengton,

Notebook 2 works fine with sketch 56+, if you can update sketch the plugin will work fine, otherwise send an email to info@owl.tools (I have checked and it's now working) and I'll send you a copy of the plugin compatible with your sketch version.

Thanks.
