### ISSUE TITLE
Notebook Pro not working on Sketch v53.2 

### ISSUE THREAD

**Issue by ladyjanuary** [marcosvidal/Sketch-Notebook#123]
I purchased the pro version from your [website](https://owl.tools/notebook-sketch-plugin). My purchase loads into Sketch (v53.2), but does not actually work once in Sketch. No sidebar ever appears with my comments. I’ve tried to toggle on and off. The only thing that shows up is an empty layer named “[nb] indicators.”

Please either fix the issue or refund my purchase.

Order number: Fsihn9U3yu7mQ9
<img width="1160" alt="Screen Shot 2019-09-26 at 8 57 57 AM" src="https://user-images.githubusercontent.com/55843107/65695229-c1776e00-e03c-11e9-8430-821d523c05be.png">

**Comment by marcosvidal** [comment]
Could you please update sketch? Notebook 2 works fine with Sketch 56+, otherwise send an email to info@owl.tools to get a copy of the plugin compatible with your sketch version.

Thanks.

**Comment by ladyjanuary** [comment]
The issue was resolved when Sketch was updated to the latest version. Thanks Marcos!
