### ISSUE TITLE
[FEATURE REQUEST] Edit the default font size, fontface and colour

### ISSUE THREAD

**Issue by katepincott** [marcosvidal/Sketch-Notebook#14]
The font size is a bit too small for my poor eyes and it is harder to read all capitals.
At the moment I edit it manually. Could I edit the default settings?

I also use https://github.com/utom/sketch-measure
They allow this in their 'settings section' 
![screen shot 2014-11-24 at 14 28 36](https://cloud.githubusercontent.com/assets/5684511/5166247/5abaaa50-73e6-11e4-9016-58907f6eacbe.png)

**Comment by pkvdesigns** [comment]
@marcosvidal is it possible to have a template sketch file in the pluginfolder that the user can style. And that the plugin uses that style from that point on?

**Comment by marcosvidal** [comment]
The new release will have this feature.
