### ISSUE TITLE
Toggle sidebar visibility shrinks artboard in case of manual turn on of sidebar visibility

### ISSUE THREAD

**Issue by Guria** [marcosvidal/Sketch-Notebook#16]
1. add sidebar.
2. run command Toggle Sidebar Visibility to hide sidebar
3. turn-on visibility of layer --nb-sidebar
4. run command Toggle Sidebar Visibility again.
5. Artboard will shrink and --nb-sidebar will be hidden.

I think some more bullet-proof method could be found to determine state of ardboard, sidebar and comments.

**Comment by marcosvidal** [comment]
Yep, I've to make it more bullet-proof. By now is better if you just rely on the command "toggle visibility".

I'll look into this. Thanks for your help :)
