### ISSUE TITLE
Page name

### ISSUE THREAD

**Issue by ozanhazer** [marcosvidal/Sketch-Notebook#21]
Thank you for the handy plugin. It would be nice if the page name is written to the sidebar too. I'm creating wireframes for the customers and export to pdf to send them since they don't have the software.
Comments are great to explain the user interface but which page is which one I have to add manually.

**Comment by marcosvidal** [comment]
Sure. I was thinking of a advanced "metadata" feature that could include page names, sections and documents covers, TOC...

Thanks for the suggestion!
