### ISSUE TITLE
This is Rad!

### ISSUE THREAD

**Issue by mikebrand** [marcosvidal/Sketch-Notebook#23]
I just wanted to thank you for making this, it's so awesome! (Sorry if this is the wrong place to post this, I was just following you give feedback link :)

**Comment by psteinweber** [comment]
It's really mind blowing how easy it is to use. Such a great plugin! Thanks a ton!

**Comment by pkvdesigns** [comment]
It is an awesome plugin, use it daily! Tweaked it a bit to fit my needs.
Changed the colors to the colors of my company and I have hidden the metadata part.

Thanks for building ;)
