### ISSUE TITLE
Relocating indicators seems to be broken

### ISSUE THREAD

**Issue by psteinweber** [marcosvidal/Sketch-Notebook#27]
It worked fine previously, but as far as I can recall there has been a Sketch update and now the comment indicators don't realign after using the shortcuts. 
I have one document with three artboards, where it works fine on one, but doesn't do anything (except a quick refresh) on the other two. I can send the document in case that isn't reproducible for others.

**Comment by jancantor** [comment]
Nudging this post as I am getting the same issue. Are there are any updates or progress on this?
I'm on 3.2.2 if that helps.

**Comment by marcosvidal** [comment]
I can't reproduce this error. Does it still seems to be broken now with 3.4.2?
