### ISSUE TITLE
Broken in 3.2.2

### ISSUE THREAD

**Issue by bzx** [marcosvidal/Sketch-Notebook#29]
Same symptoms as in https://github.com/marcosvidal/Sketch-Notebook/issues/17

I've tried re-installing the plugin via SketchToolbox with no luck.

**Comment by benberte-mdsol** [comment]
Any update on this? Also broken for me on 3.2.2.

**Comment by dnlswan** [comment]
I'm also having these same issues which is unfortunate because I was planning to use it today.

**Comment by benberte-mdsol** [comment]
@dnlswan I actually got mine working. Make sure your file is a new Sketch 3.2.2 file and it should work. For some reason I could not get the notebook to work on older files.

**Comment by dnlswan** [comment]
@benberte-mdsol I created files from scratch in 3.2.2 and I'm just still getting the same issues unfortunately.
