### ISSUE TITLE
Dynamically updating header, metadata, screen name

### ISSUE THREAD

**Issue by bfullest** [marcosvidal/Sketch-Notebook#30]
Hello! I love your product! There are only a couple things that are a bit frustrating to me - all around dynamically updating data. 

1. If I update the header and metadata at the page level (--nb--assets) and create a new sidebar on a new artboard, the updates appear (yay!). But if I have already created sidebars, they do not update when I change the --nb--assets page. 

2. If I update the title of my sketch document, the "project" name is not automatically updated in the sidebar - I have to do that manually.

3. If I change the name of an artboard in the artboard/layer panel, it is not automatically updated in the sidebar - I have to do that manually (TO ME THIS IS MOST IMPORTANT).

4. The date is not dynamic, so it cannot reflect a "modified on" date automatically.

**Comment by marcosvidal** [comment]
The new release will have this feature.
