### ISSUE TITLE
[Feature request] Change position of the circle

### ISSUE THREAD

**Issue by pkvdesigns** [marcosvidal/Sketch-Notebook#33]
I would like to be able to change the position of the balls manually. I can unlock the balls group and reposition the ball, however when I use cmd+alt+ctrl+8 the ball goes back to the original position.

**Comment by colbydodson** [comment]
This would be very helpful for me as well.

**Comment by lostsatellites** [comment]
+1

**Comment by danmindru** [comment]
+ 1

**Comment by anasqtiesh** [comment]
This would be immensely helpful. The auto location is rarely where I need the indicator to be.

**Comment by jay-bee-why** [comment]
+1

**Comment by MintCondition** [comment]
+1

**Comment by marcosvidal** [comment]
The new release will have this feature.
