### ISSUE TITLE
[Feature request] Balls with arrows

### ISSUE THREAD

**Issue by pkvdesigns** [marcosvidal/Sketch-Notebook#35]
It would be nice to be able to give a direction to a comment (see image below). This means 8 pointed balls to choose from when creating a comment.
![pastedgraphic-1](https://cloud.githubusercontent.com/assets/5709624/6919497/d0dc3462-d7b7-11e4-8906-8dac4a02d428.png)

Thanks in advance!

**Comment by marcosvidal** [comment]
Great feature. I'll think how to add this.
