### ISSUE TITLE
Sketch-Notebook not working in Sketch 3.3

### ISSUE THREAD

**Issue by alexcolbeck** [marcosvidal/Sketch-Notebook#37]
Sketch-Notebook not working in Sketch 3.3

**Comment by aa-wilson** [comment]
Having same issue

**Comment by tomvb** [comment]
Same! :cry:

**Comment by colbydodson** [comment]
Same- screen goes blank.

**Comment by dacuima** [comment]
Same! :cry:Same! :cry:Same! :cry:

**Comment by dacuima** [comment]
Developers do not update yet

**Comment by Julyyq** [comment]
Same! 😢

**Comment by mxmcsc** [comment]
Hi boys and girls, you can download the previous version here: https://dl.dropboxusercontent.com/u/93762/older-versions/sketch-3.2.2.zip

**Comment by dacuima** [comment]
You know, Sketch team more annoying is that the low version can not open a file created by the high version

**Comment by mattbogado** [comment]
What is a good alternative to this plugin?

**Comment by bomberstudios** [comment]
> the low version can not open a file created by the high version

You can always try copying & pasting from 3.2.2 to 3.3. That should work unless your design is *really* complex.

I'll take a look at the plugin's code and see what I can do…

**Comment by bomberstudios** [comment]
Here's a fix for it, hope it gets merged soon : )

**Comment by Julyyq** [comment]
@bomberstudios You are awesome!

**Comment by dacuima** [comment]
@bomberstudios You are awesome awesome! awesome!awesome!awesome!awesome!awesome!awesome!awesome!awesome!awesome!awesome!awesome!awesome!awesome!awesome!awesome!awesome!awesome!awesome!awesome!awesome!awesome!awesome!awesome!awesome!awesome!awesome!awesome!awesome!awesome!awesome!

**Comment by dacuima** [comment]
@bomberstudios Date created some problems later, you can look at it?

**Comment by dacuima** [comment]
@bomberstudios Very strange phenomenon![2015-04-16 2 31 41](https://cloud.githubusercontent.com/assets/8212878/7175288/65d1d268-e445-11e4-960d-565e35cd5400.png)
![2015-04-16 2 31 53](https://cloud.githubusercontent.com/assets/8212878/7175291/6a8691b8-e445-11e4-80ba-12121ca28fc9.png)

**Comment by dnlswan** [comment]
I can't say that the fix @bomberstudios made actually made any changes for me. Should I just clean install sketch or roll back to 3.2.2?

**Comment by colbydodson** [comment]
Is there any sort of timeline when this will be fixed? Just curious before I revert back to 3.2.2

**Comment by prerakpatel** [comment]
@bomberstudios Can you walk through the fix you referenced for v3.3? Can't seem to get it. Would appreciate your help.

**Comment by psteinweber** [comment]
Same here :)

**Comment by williamli** [comment]
there is a fix over at https://github.com/getflourish/Sketch-Notebook/commit/3e8643cd7dd89d06f2929d95ef4b3830e2fc5bee for this.

**Comment by zhouxl** [comment]
@williamli already exist

**Comment by dnlswan** [comment]
@williamli Thank you for sharing, this fix works for me on 3.3.1!
