### ISSUE TITLE
REQUEST: Toggle visibility of all notebooks

### ISSUE THREAD

**Issue by mason72** [marcosvidal/Sketch-Notebook#38]
LOVE the Sketch Notebook plugin! One thing I would love to be able to do is toggle the open/closed state for an entire document at once. I find that when I'm presenting I'd like to turn all of my documentation notes off. 

Thanks!

**Comment by melissakeizer** [comment]
+1 for this!

**Comment by marcosvidal** [comment]
The new release will have this.
