### ISSUE TITLE
Plugin not working in sketch version 3.3

### ISSUE THREAD

**Issue by pedrodoo** [marcosvidal/Sketch-Notebook#43]
Hello Marcos,

So I tried to install and run the plugin, but it's not working. 
When I try to add a comment, it opens another page in the same document that I'm working in, with the name --nb--assets. I think a pop-up is supposed to appear.
I'm using sketch's 3.3 version.

Thanks in advance for your help and kudos for what looks like an awesome plugin!
Pedro

**Comment by getflourish** [comment]
There are a few things that changed in 3.3. I will look into it over the weekend, as I found a few great use cases for the plugin.

**Comment by Burbur2088** [comment]
Thank you so much, Getflourish!

**Comment by getflourish** [comment]
Fixed this and created a pull request. Please test it: https://github.com/getflourish/Sketch-Notebook

**Comment by pedrodoo** [comment]
It's working! Thank you!
