### ISSUE TITLE
Notebook plugin does not work on Sketch 3.3.1

### ISSUE THREAD

**Issue by zyltd1990** [marcosvidal/Sketch-Notebook#45]
Hey, I have installed the plugin and uninstalled it for a couple of times. It only create a new page the first time I add a comment. I can not edit it after that.

**Comment by finlaycraig** [comment]
Agreed. Behaving strangely.

**Comment by getflourish** [comment]
Fixed this and created a pull request. Please test it: https://github.com/getflourish/Sketch-Notebook

**Comment by dennismaij** [comment]
It Works except for updating the comment.

**Comment by llong** [comment]
Confirming that it's working aside from updating comments

**Comment by getflourish** [comment]
What do you expect, that does not happen?

**Comment by dennismaij** [comment]
It doesn't show a editing window. I edited my comments now by going into the layers which the plugin creates.
