### ISSUE TITLE
Sketch-Notebook does not work for version 3.3.1

### ISSUE THREAD

**Issue by yujuns** [marcosvidal/Sketch-Notebook#47]
It opens a new page, and creates new layers. But the comment box does not show up.

**Comment by clabap** [comment]
+1

**Comment by williamli** [comment]
+1

**Comment by williamli** [comment]
there is a fix over at https://github.com/getflourish/Sketch-Notebook/commit/3e8643cd7dd89d06f2929d95ef4b3830e2fc5bee for this.
