### ISSUE TITLE
not working with Sketch 3.3.1

### ISSUE THREAD

**Issue by riskiii** [marcosvidal/Sketch-Notebook#48]
I am not having any luck with the latest Sketch and Notebook.  When I add an item, it does not create the addition to the artboard, nor does it add any data items.  There is only one folder, not two.  Attaching screenshot.
![northwood_sketch](https://cloud.githubusercontent.com/assets/1524635/7435432/477fc6d8-f009-11e4-9275-f08b7e420594.png)

thanks in advance

**Comment by williamli** [comment]
@riskiii there is a fix over at https://github.com/getflourish/Sketch-Notebook/commit/3e8643cd7dd89d06f2929d95ef4b3830e2fc5bee for this.

**Comment by navneetnair** [comment]
Tried that, did not work for me...

**Comment by williamli** [comment]
strange. works fine for me

**Comment by navneetnair** [comment]
Uninstalled the plugin. Re-installed and then made the change. Works :+1:
