### ISSUE TITLE
Trouble with  Sketch version 3.3.2

### ISSUE THREAD

**Issue by travisbsmith** [marcosvidal/Sketch-Notebook#51]
I love the idea of this plug-in but have never gotten it to run correctly in the latest versions of Sketch  3.3.2. I have tried using the keyboard shortcuts and the menu commands, but nothing happens. The --nb--balls layers are created, but I cant see or add any comments.

Thanks!
Travis

**Comment by johnend** [comment]
Agreed, same thing happened to me today, the input box does not show up for documenting titles or comments. A new page opens in Sketch with the --nb--stuff layer, which is a small rectangle with no attributes for fill or border etc. and nothing shows up on the main artboard.

I would love for this plugin to work, will be extremely useful for me in the future!

**Comment by travisbsmith** [comment]
I am having 100% the same experience as johnend. This plugin would be worth paying for, IMO.

**Comment by fabnoe** [comment]
Same here!

**Comment by jtwhite14** [comment]
Same here - just get a new page bu no popup to add comments :cry:

**Comment by jtwhite14** [comment]
FYI - just tried this [getflourish@3e8643c] (https://github.com/getflourish/Sketch-Notebook/commit/3e8643cd7dd89d06f2929d95ef4b3830e2fc5bee) and it worked :smile:

**Comment by johnend** [comment]
Yep the above definitely works, have to go through manual install for those who tried to find it on Sketch Toolbox.
