### ISSUE TITLE
For some reason this plugin isn't working for me

### ISSUE THREAD

**Issue by jamiedarcher** [marcosvidal/Sketch-Notebook#53]
I tried to add a comment but the dialog box to add comments is not appearing when I hit the key combination or use the menu item - a layer is being created for comments but it does not show up ie. its not visible. 

Please advise what should I do are there conflicts with other sketch plugins?
Should I have my document set up in a certain way.

I really need the functionality this plugin offers so any help would be much appreciated

**Comment by oojikoo-gist** [comment]
@jamiedarcher what version are you using? You need to use the latest version of Sketch. That happened to me a long time ago, and updating it solved the problem.

**Comment by oojikoo** [comment]
@jamiedarcher what version are you using? You need to use the latest version of Sketch. That happened to me a long time ago, and updating it solved the problem.
one more thing, are you using sketch toolbox?

**Comment by jamiedarcher** [comment]
Yes I'm using sketch toolbox and the version of sketch is Version 3.3.2 (12043)

**Comment by oojikoo** [comment]
@jamiedarcher the latest version of sketch is 3.3.3, updating it will solve user problem. this plugin didn't work before I updated, I remember.

**Comment by jamiedarcher** [comment]
Okay I just updated still don't see the dialog boxes when I hit the key combo

**Comment by jamiedarcher** [comment]
I'll try uninstalling and reinstalling the plugin

**Comment by jamiedarcher** [comment]
Still not working is there a way I can supply you with better debug info?

**Comment by jamiedarcher** [comment]
Have you had any other comments about this version or is it working fine for you?

**Comment by jamiedarcher** [comment]
Seems to be working in a new file I created so I can't figure out why its not workin in the other one - great plugin by the way!

**Comment by anketwokings** [comment]
Same issue here in an existing document; 
I tried uninstalling and installing the plugin, always automatically update my Sketch, but it only creates a layer called 'nb-assets'. No dialogue appears to enter my comments.
(The document has multiple artboards in multiple pages.)

Created new file with new artboard and new pages: 
No problem anymore, the plugin works normal again. Magic..

**Comment by macbruker** [comment]
Plugin isn't working for me. Reinstalled latest Sketch from App Store and grabbed a fresh download of Sketch-Notebook. 

Here is what I am doing:
1. Add a new comment.
2. A new page called `--nb--assets` is created by the plugin
3. Add a new comment
4. A new layer group called `--nb--assets` is created in the page my design is in.
5. Nothing happens …

The plugin idea is great, and I gladly payed for it, so I'm hoping there some kind of solution is coming soon.

**Comment by marcosvidal** [comment]
It should be working now.
