### ISSUE TITLE
Not All Fields in Notebook Asset Page have Styles

### ISSUE THREAD

**Issue by bennyp123** [marcosvidal/Sketch-Notebook#59]
`sidebar/metadata/label_Project` and `sidebar/metadata/value_Untitled` have styles (`nb:assets:metadata:label` and `nb:assets:metadata:value`) but `sidebar/metadata/label_Date` and `sidebar/metadata/label_Author`, or their values, do not (they should!)
`header/Sketch Notebook` has no style
`label_screen` has no style
`bottomLine` have no styles

**Comment by marcosvidal** [comment]
The new release will fix this.
