### ISSUE TITLE
Dates aren't working

### ISSUE THREAD

**Issue by ngov** [marcosvidal/Sketch-Notebook#61]
I added a comment to a Sketch document that had previously had comments, but the date is wrong. It shows the same date as the old comments, but I'm not sure that those comments even have the right date. New documents don't have the right date either.

The only change I've done was to the master board (--nb--assets) so that the fonts were a little more readable.

Running Sketch v. 3.4.2

**Comment by marcosvidal** [comment]
Fixed. The new release will update the dates correctly.
