### ISSUE TITLE
Update comments

### ISSUE THREAD

**Issue by ssutcher** [marcosvidal/Sketch-Notebook#63]
My update comments feature doesn't seem to be working. If I update a comment layer, or even rename the art board, the plugin ceases to function at all. Please help!

**Comment by marcosvidal** [comment]
Hello @ssutcher!

Where did you get the plugin from? How did you install it? What version of sketch are you using?

**Comment by ssutcher** [comment]
Running:
Version 3.4.2 (15857)

Downloaded and installed using:
Sketch Toolbox

Steps to reproduce.
1. Create a comment on an element on an artboard in a brand new sketch file.
2. Update the body text of the comment
3. Run update comments
4. Try to comment on another element. Get an error sound

**Comment by marcosvidal** [comment]
Please try using the latest release, donwloading it from here: http://marcosvid.al/sketch-notebook

**Comment by ssutcher** [comment]
Hi @marcosvidal just downloaded the pro version and installed. Still seem to be having the same issue.

**Comment by marcosvidal** [comment]
Do you have multiple sketch documents opened?

**Comment by ssutcher** [comment]
@marcosvidal yes - definitely have multiple documents open.

**Comment by marcosvidal** [comment]
This is the only way I can reproduce the issue. Could you please try to use the plugin with just one document opened? 

If this is the cause, it's a strange bug from sketch that I thought were fixed on 3.4.2... let me look into it.

**Comment by ssutcher** [comment]
Hi @marcosvidal updated sketch to Version 3.4.3 (16044) and it seems to be fixed. Thanks!
