### ISSUE TITLE
No longer working in sketch 3.7.1

### ISSUE THREAD

**Issue by ssutcher** [marcosvidal/Sketch-Notebook#65]
I seem to be having a problem in with the plugin in sketch 3.7.1. On adding a comment, it creates a new page (like it used to) then it takes me to that page and creates a black box with "notes" at the top (see screenshot below). It never actually gives me the pop-up to add the comment.

Then when I go back to the artboard there is no sidebar or comment, or even text box to enter the comment.

Then, if I toggle the sidebar on that artboard (thinking it is hidden) it actually decreases the width of the artboard cutting of the design. 

![screen shot 2016-04-19 at 12 39 32 pm](https://cloud.githubusercontent.com/assets/3875980/14653021/e3c09b88-062b-11e6-8ee2-1e6c25760233.png)

**Comment by alyssatucker** [comment]
I am having the same issue. Seems to have broken when Sketch updated how it handles symbols. I was able to expand my artboard to see the notes symbol that was added, though when I try to add a comment, it now freezes Sketch and causes it to crash.

**Comment by marcosvidal** [comment]
@ssutcher @alyssatucker there was a plugin update a few days ago.

Please try to download the plugin again, reinstall it, and then relaunch sketch. It should be working then.

**Comment by cblevinsajc** [comment]
When I toggle view sidebar, the app eventually crashes Sketch 3.7.1.  Adding comments, slows the app heavily, sidebar gets through various sates of building, very slowly and eventually flushes the app.
Have reinstalled the app and the plugins, no help

**Comment by cblevinsajc** [comment]
I deleted and reset the assets and that seems to have resolved it.

**Comment by marcosvidal** [comment]
Nice! Let me know if you have any other issue :)

**Comment by ssutcher** [comment]
Thanks for the quick notes back @marcosvidal! Everything seems to be working now.

**Comment by alyssatucker** [comment]
Thanks! It works now!

**Comment by paulfey** [comment]
Hi @marcosvidal I've just been having the same problem as the above but I only get a grey box when I try to add a comment. I was a frequent user of notepad last year and never had a problem. I have deleted the plugin and re-installed it and quit Sketch and re-booted my Mac but still having the same problem. Can you help? 
![screen shot 2016-11-09 at 15 24 35](https://cloud.githubusercontent.com/assets/23361447/20143427/e109349e-a690-11e6-999d-7766c609580c.png)

**Comment by lavvinat** [comment]
@marcosvidal I just got the plugin today and I am having the same issues as Paulfey

**Comment by marcosvidal** [comment]
@lavvinat please try to reset the assets, it should be working fine with sketch 41

**Comment by chloebarbieux** [comment]
Hey Marcos, i just bought the plugin and installed it , it doesn't show up in the plugin drop down. 
I uninstalled it, reinstalled, restarted sketch. Nothing :/

I opened the manage plugin. Made sure it was enabled. And still nothing. Can you please help ?

**Comment by marcosvidal** [comment]
Hi @chloebarbieux 

what Sketch version are you using?

**Comment by rachelferreira26** [comment]
I just bought the plugin and installed it. I'm able to add a note, but I only get a grey box added to the screen that says "SCREEN" and a new page, assets, with a black art board that just has project, date, and author. Any ideas?

**Comment by chac3x** [comment]
in current version of sketch, plugin doesn't work for me.

**Comment by giaphua** [comment]
Hi Marcos, I bought your USD 7.99 plugin, and it doesn't work on Sketch version 44.1. I have emailed you on the 1st June 2017, and have not received a reply from you.

It seems like the same problem has been constantly reported on this plugin for all the updated versions of Sketch. Can you see to this problem quickly? I've been using this feature and it's a disruption to my workflow without it. 

If you cannot resolve this issue, can you kindly refund the money I've paid for your plugin? My Reference #: 170601-1426-201192

**Comment by studiotemple** [comment]
Hi Marcos, How can I change the width of the sidebar?
