### ISSUE TITLE
Month number in Date in Notebook Panel is off by 1

### ISSUE THREAD

**Issue by damenleeturks** [marcosvidal/Sketch-Notebook#66]
Today is April 29 (i.e., `4/29/2016`), but when I run the plugin, I get `3/29/2016`in the sidepanel's header. I'm not sure what's happening. 

![image](https://cloud.githubusercontent.com/assets/259759/14929076/ebfdab02-0e18-11e6-88de-2a12b38d0f77.png)

**Comment by damenleeturks** [comment]
Any idea when this might get fixed, @marcosvidal?

**Comment by micheletepper** [comment]
I am having the same issue.
