### ISSUE TITLE
NB lite broken out of the box

### ISSUE THREAD

**Issue by mars1980** [marcosvidal/Sketch-Notebook#68]
Running sketch 3.7.2 on OSX 10.11.4

*when I try to add a comment, it populates with empty assets/shapes?

![screen shot 2016-05-20 at 11 48 50 am](https://cloud.githubusercontent.com/assets/2332434/15433630/1bbe74d4-1e81-11e6-8603-46522ce3fafe.png)
![screen shot 2016-05-20 at 11 49 03 am](https://cloud.githubusercontent.com/assets/2332434/15433631/1bbef51c-1e81-11e6-92b3-fefa66d5f937.png)

**Comment by marcosvidal** [comment]
Hey Cris! Please update Sketch to 3.8 and let me know how it works.

**Comment by mars1980** [comment]
done! strange, works on my 'notes' art board but having the same issue on the art board I want to put in the notes. 
![screen shot 2016-05-20 at 3 15 47 pm](https://cloud.githubusercontent.com/assets/2332434/15439219/e2746018-1e9d-11e6-873d-290854bd6a59.png)

**Comment by mars1980** [comment]
I just put everything on a new art board and its fine. thanks!

**Comment by mars1980** [comment]
the dates in the comments say 4/20/16 instead of 5/20. just a heads up
