### ISSUE TITLE
The plugin no longer works with the Sketch v.39

### ISSUE THREAD

**Issue by emersive** [marcosvidal/Sketch-Notebook#72]
The plugin no longer works with the Sketch v.39. It makes everything on the screen disappear. Zooming out doesn't make a difference.

**Comment by clabap** [comment]
+1

**Comment by j5uh** [comment]
+1

**Comment by zozomoey** [comment]
I just purchased the pro version and it's note working anymore? :(

**Comment by marcosvidal** [comment]
I've just updated the plugin. Please download the latest version.
