### ISSUE TITLE
Broken on 39.1?

### ISSUE THREAD

**Issue by jawgrip** [marcosvidal/Sketch-Notebook#75]
Anyone else unable to use the Pro plugin in 39.1?

We've tried on multiple machines to no luck.

Plugin is updated to latest - 0.3.

**Comment by Ryan529** [comment]
Broken for me as well. The note gets cut off next to the artboard, with the rest of the info placed somewhere off of the artboard above it.

**Comment by rbouajram** [comment]
I just bought the Pro version and I can confirm it's broken on my end too.  Same behavior.

**Comment by paulfey** [comment]
Same here, @marcosvida can you help?

**Comment by marcosvidal** [comment]
Hey guys, thanks for your patience! I've just updated the plugin to work with Sketch v41. This should be solved now.
