### ISSUE TITLE
Toggle visability issue

### ISSUE THREAD

**Issue by 360spencer** [marcosvidal/Sketch-Notebook#76]
When toggling visibility on & off plugin is adding additional space between artboards, each toggle will add more and more space between them. when toggling off note, artboards collide and overlap. 
Strange this is only happens to about 1/2 of my artboards on the same page, all others act as intended, keeping the correct spacing.
Sketch 40
OSX 10.12

**Comment by marcosvidal** [comment]
This is the first time I see this. Can you confirm that this happens with a document made from scratch?
