### ISSUE TITLE
Not working for 40.3?

### ISSUE THREAD

**Issue by kameronahler** [marcosvidal/Sketch-Notebook#77]
I'm curious if this version is working for 40.3? I'm unable to see comments in the sidebar (or the sidebar at all) http://recordit.co/1zm01IPVgS

I was hoping to try this before buying it.

**Comment by marcosvidal** [comment]
Hi @kameronahler , yes I can confirm that it works with Sketch v41 (35326). Feel free to conotact me with any doubts or suggestions.
