### ISSUE TITLE
No longer working in Sketch version 41

### ISSUE THREAD

**Issue by paulfey** [marcosvidal/Sketch-Notebook#78]
Hi @marcosvidal I've just been having the same problem as the guys had on thread [(https://github.com/marcosvidal/Sketch-Notebook/issues/65)](https://github.com/marcosvidal/Sketch-Notebook/issues/65) but I only get a grey box when I try to add a comment. I was a frequent user of notepad last year and never had a problem. I have deleted the plugin and re-installed it and quit Sketch and re-booted my Mac but still having the same problem. Can anyone help? 
![screen shot 2016-11-09 at 15 24 35](https://cloud.githubusercontent.com/assets/23361447/20145660/dde578d8-a698-11e6-9c4b-947fcdc3abbd.png)

**Comment by mcarlile** [comment]
I'm also having the same grey box issue when attempting to generate comments after updating to Sketch 41. I use this plugin every day and am really looking forward to a resolution!

**Comment by lavvinat** [comment]
Hi @marcosvidal This is not working for me on sketch version 41 as well. Having the same issues as reported above

**Comment by johnnyjiangyc** [comment]
I just bought the pro version, It doesn't work at sketch 41

**Comment by marcosvidal** [comment]
Hi guys! Thanks for your patience. I've just updated the plugin and can confirm that it's working fine with Sketch Version 41 (35326). Please let me know if you have any other issues or comments.

**Comment by mcarlile** [comment]
Thanks!

**Comment by rachelferreira26** [comment]
What about version 42, it's an issue again.
