### ISSUE TITLE
Issues with existing Sketch files

### ISSUE THREAD

**Issue by datapanda** [marcosvidal/Sketch-Notebook#79]
Hello,

I have a large project that I want to use Sketch Notebook with. However, when I go to add annotations they do not show up properly. The comments are off the artboard and above the top of the comments section. 

The issue appears to be when working with an existing Sketch file versus a new Sketch file. 

![screen shot 2016-11-14 at 9 18 40 am](https://cloud.githubusercontent.com/assets/2712297/20268025/61b70b4e-aa4b-11e6-9a2c-28d1c2b9a62c.png)

**Comment by gbenitezdelugo** [comment]
The same happens to me. 

Comments are added but further to the top so they aren't visible
Update command don't work either

**Comment by gbenitezdelugo** [comment]
Just realized the issue.

I'm using 2 Sketch versions:
* I use v39.1 cause it's much quicker.
The Sketch support team told me to keep this version for long projects.
In this version the plugin works as reported by @datapanda and me

* I also use Sketch Beta for some other new functionalities
I this version it works perfectly

@marcosvidal I'd love to run this plugin in the v39.1 version - is it possible to support it?

@datapanda check and install updates for Sketch and it will work perfectly!

Best to everybody!

**Comment by datapanda** [comment]
@gbenitezdelugo - It's not the version issue of sketch that's the problem for me. If I use the latest version of Sketch with a **NEW** file it works fine. However, if I use the latest version of sketch with an **EXISTING** file - that's when I get the issue.

**Comment by marcosvidal** [comment]
Maybe if you try to reset the assets (delete all --nb--* pages and symbols) it will work with previous annotated files.

@gbenitezdelugo contact me through www.marcosvid.al and i'll send you a copy working with sketch 39.

Cheers.

**Comment by datapanda** [comment]
@marcosvidal - Sorry I'm talking about existing Sketch files. Not existing Sketch files with Sketch Notebook assets. 

e.g. 
Day 1: Create a sketch file <myfile.sketch> with some assets, a lot of assets and pages, etc. 
Day 2: Purchase Sketch Notebook and install
Day 3: Add Sketch Notebook notes to myfile.sketch -> **issue exists**
Day 4: Create a new sketch file <mynewsketchfile.sketch>
Day 5: Add Sketch Notebook notes to mynewsketchfile.sketch -> works fine

Does that timeline make sense of the issue? The files created AFTER installing Sketch Notebook in this timeline work fine but previous files that were created BEFORE have the issue.

**Comment by marcosvidal** [comment]
I've tried to comment a document from 9 feb 2015 and it worked fine. It might be the version you're using. PLease make sure it's the latest and that the assest have been generated with it.

Let me know if I can help you with anything else.

**Comment by SimplyPhy** [comment]
I can confirm this is an issue in Sketch 41.2.  Existing saved projects [all started within 41.2] (prior to install of Sketch Notebook) will produce the result demonstrated in the OP's screenshot.

Creating a duplicate (cmd+shift+s) of the project retains the issue, though creating a new project and copy/pasting artboards from original project fixes the issue for me.

**Comment by jamiemill** [comment]
I'm also having this problem with my project.

I can reproduce the problem if I create a new Sketch document from the "Web Design" template and then try to insert a comment on the first artboard of the first page. See this screencast: http://recordit.co/rgwFFDwIqH

There seems to be something about the "Symbols" page in this template (which my project probably inherited) that confuses this plugin. There's something strange in the first place with the fact it has two "Symbols" pages. Deleting the first one fixes the problem, as does renaming it. But deleting/renaming the second doesn't.

I think I've found a way to fix it (if you don't mind losing your comments):

1. create a brand new sketch document (not using a template)
2. insert a comment on an object
3. go to the generated --nb--assets page
4. copy the two layers in there to your clipboard
5. switch to your broken document
6. delete the two layers in your --nb-assets page, and paste in the version from your clipboard
7. go to Plugins> Notebook Pro > Tools & Settings > Reset Comments (you will lose all your comments)
8. insert a new comment

It seems like this will cause the plugin to use the non-broken --nb-assets as a template from now on.

I'm using the Pro version (just paid+downloaded today) on Sketch 43.2.
