### ISSUE TITLE
Not working in Sketch 41

### ISSUE THREAD

**Issue by WhatsNewSaes** [marcosvidal/Sketch-Notebook#81]
When I try to add a comment it adds `--nb--assets` as a page with a large gray rectangle on the canvass, but no side panel on the actual commented artboard. Is this a known issue or is it just me?

**Comment by avrieloconnor** [comment]
Not just you! Happening to me too. Just a gray rectangle.

**Comment by WhatsNewSaes** [comment]
@marcosvidal any help you can provide would be greatly appreciated!

**Comment by marcosvidal** [comment]
Hey guys! The plugin should be working fine. Did you get the last update?

**Comment by avrieloconnor** [comment]
@marcosvidal Just go the update and tried it. It's working! Thanks so much. I did some annotations manually the other day, SO HAPPY to have this back up and running. Thanks again.

**Comment by WhatsNewSaes** [comment]
Agreed. Looks like it's working perfect now. Thanks @marcosvidal!
