### ISSUE TITLE
Notebook Premium for Sketch 42 Issues

### ISSUE THREAD

**Issue by nison** [marcosvidal/Sketch-Notebook#84]
I'm experiencing the following issues in Sketch 42 with the latest notebook. I can no longer use it.

1. Add comments inconsistently stops working on artboards and for all subsequent artboards
2. Styles is missing in the Notebook Nav
3. Metadata not updating

Anyone else?

**Comment by tvachon** [comment]
I ran into a similar issue recently where the comments would work on some artboards and not others. After some poking around I figured out that I had an existing  '--nb--sidebar' layer that I had accidentally added some content to...and I'd been duplicating that artboard as I was creating new screens. That was causing the create comment script to bomb. 

Once I found and renamed that layer, everything worked fine.

**Comment by WuliuLyyi** [comment]
I have the same issue as well. I reinstalled it several times, but still does not work.

**Comment by marcosvidal** [comment]
Make sure you are using the latest version of the plugin. Everything is working smoothly.
