### ISSUE TITLE
Layout Broken in Sketch 42

### ISSUE THREAD

**Issue by sophiamf** [marcosvidal/Sketch-Notebook#85]
Layout Issue:
<img width="609" alt="screen shot 2017-02-21 at 10 20 48 am" src="https://cloud.githubusercontent.com/assets/10751578/23224148/2e2902b0-f8fb-11e6-8b33-6093d3286c71.png">

Sketch Version: Sketch 42
OS: 10.12.1

List of other plugins/potential conflicts:
<img width="304" alt="screen shot 2017-02-21 at 10 23 58 am" src="https://cloud.githubusercontent.com/assets/10751578/23224161/35816ab6-f8fb-11e6-8f13-21e99b14d2e9.png">

**Comment by rebz** [comment]
Layout is still broken. Creator is unresponsive via email.

**Comment by marcosvidal** [comment]
Make sure you are using the latest version of the plugin.
