### ISSUE TITLE
Sketch 43.2

### ISSUE THREAD

**Issue by raymayfield** [marcosvidal/Sketch-Notebook#89]
Notebook constantly crashes on 43.2 when I go to add a comment. If I change any style it will also crash on adding a comment.

**Comment by dave-regan** [comment]
I was unable to use the plugin at all on v43.

Fortunately, I was planning on updating anyway. But this issue should be made clearer before you accept payment for this plugin.

**Comment by marcosvidal** [comment]
Make sure you are using the latest version of the plugin.
