### ISSUE TITLE
Notebook side panels not sizing to artboards

### ISSUE THREAD

**Issue by bkitko** [marcosvidal/Sketch-Notebook#93]
This issue has happened twice now in different files but I can't replicate in on demand. I don't know what is triggering it. Something is causing notebook side panels to not resize to the artboard when updated so they end of looking messy.

![screen shot 2017-06-06 at 3 01 42 pm](https://user-images.githubusercontent.com/29238163/26849262-1b2cd338-4ac9-11e7-8045-876ce46c8a72.png)

**Comment by marcosvidal** [comment]
I'm not able to reproduce this bug.... Maybe if you reset the assets it will work fine again.

**Comment by bkitko** [comment]
How do you reset assets? I see reset comments, which deletes them all, and update comments, which does not fix the issue.

**Comment by marcosvidal** [comment]
Delete the page --nb--assets and every symbol related to the plugin.

**Comment by bkitko** [comment]
And then update comments? Will that not unlink all instances of those symbols, meaning I'd have to manually recreate all the comments?

**Comment by marcosvidal** [comment]
Then add another comment.

**Comment by bkitko** [comment]
That did not resolve it. I will like manually adjust it before delivery.
