### ISSUE TITLE
Problem with Annotations Notebook Plugin from marcos vidal, in Sketch version 44.1 

### ISSUE THREAD

**Issue by giaphua** [marcosvidal/Sketch-Notebook#94]
@marcosvidal    I'm having a problem in with this Notebook plugin in Sketch 44.1. 

On adding a comment, it creates a new page and then it takes me to that page and creates a black box with "notes" at the top (see screenshot below). It never gives me the pop-up to add the comment.
Then when I go back to the artboard there is no sidebar or comment, or even text box to enter the comment.

Then, on the artboard, if I press cmd+option+ctrl+9 on any elements, the sidebar will be applied on the artboard, but it is hidden at the right side of the artboard. Unless I expand the artboard's width, I won't see it. Nonetheless, the nb balls still do not appear after using cmd+option+ctrl+9.  

<img width="813" alt="screen shot 2017-06-07 at 7 00 47 am" src="https://user-images.githubusercontent.com/24440373/26856028-d0f8819e-4b50-11e7-9372-37698ccaa38e.png">
<img width="882" alt="screen shot 2017-06-07 at 7 01 44 am" src="https://user-images.githubusercontent.com/24440373/26856029-d131d476-4b50-11e7-9fae-91c101fa73fe.png">

--------------------------------------------------------------------------

@marcosvidal  I bought your USD 7.99 plugin, and it doesn't work on Sketch version 44.1. I've emailed you on the 1st June 2017, and have not received a reply from you. If you cannot resolve this issue, can you kindly refund the money I've paid for your plugin? My Reference #: 170601-1426-201192   Thanks.

**Comment by max1mvs** [comment]
I had the same issue, and I managed to install an update for the plugin. The issue disappeared afterwards (Sketch 44.1, Plugin v.0.44).

**Comment by JetPack33** [comment]
@max1mvs Is plugin v.0.44 free or is it a priced version?

**Comment by max1mvs** [comment]
@JetPack33 Priced.

**Comment by dusskapark** [comment]
I had the same issue and followed @max1mvs' tips but it's still occurred...

**Comment by dragonflyATL** [comment]
@giaphua has this issue been fixed for you yet? I just downloaded the Pro version and am having the same issues with Sketch v45.2

**Comment by marcosvidal** [comment]
I already published an update to fix this. In any case guys, this repository is not meant for giving support to Pro users... please follow the corresponding channels of communication.

**Comment by dragonflyATL** [comment]
I emailed you via to channel of communication ie. support@marcosvid.al 
I have yet to hear back from you. Please respond as I have already paid for this download.

**Comment by dragonflyATL** [comment]
I will send another email if that helps. I'l send it to the same address: support@marcosvid.al

**Comment by marcosvidal** [comment]
With every sketch update that made the plugin stop working I released a fix and sent and email to every user. Just check you inbox.

Also, I recently published a version with new features for sketch 45. You can download it for free if your purchase was after June 1st 2017 or if you have a premium license. Otherwise you'll have to purchase the plugin again to support the development :)

I also reply to every mail, even though only the premium users have personal support. I've checked and cannot find anything related to "dragonfly atl". Which email address did you use to contact me?

Cheers,
Marcos.
