### ISSUE TITLE
Key Commands not working Sketch v.44.1

### ISSUE THREAD

**Issue by daigerj** [marcosvidal/Sketch-Notebook#97]
I updated to the newest plugin version Notbook Pro 0.44 as well as themost updated Sketch 44.1. In this version of sketch I am not able to use key commands to create new notes, hide and view notes or any other commands.

**Comment by marcosvidal** [comment]
I can't reproduce this issue. It works fine in my computer ;)

If you are using one of the latest macbook pro's... maybe you are having issues with your keyboard.
