### ISSUE TITLE
Can't Edit Comments

### ISSUE THREAD

**Issue by Sage911** [marcosvidal/Sketch-Notebook#98]
When I select the comment body layer in the sidebar, then double click into the text box, Sketch unselects the layer.

**Comment by marcosvidal** [comment]
I already published an update to fix this.

**Comment by Sage911** [comment]
Sweet, thank you

On Jul 18, 2017, at 12:52 PM, Marcos Vidal <notifications@github.com<mailto:notifications@github.com>> wrote:


I already published an update to fix this.
