### ISSUE TITLE
Toggle visibility conflict on 44.1

### ISSUE THREAD

**Issue by dave-regan** [marcosvidal/Sketch-Notebook#99]
Manually hiding the sidebar causes 'Show all sidebars' to add extra space to the side of the artboard. Problem arising in Sketch v44.1. Steps to reproduce:

1. Add comment to layer
2. Manually hide '--nb--sidebar' group
3. Select 'Show all sidebars'
4. Sidebar is shown, but artboard whitespace allocated to notes has doubled in width

![Replication](https://user-images.githubusercontent.com/5868691/27484644-df08bf32-5821-11e7-97aa-31e5ae6b6a84.gif)

**Comment by marcosvidal** [comment]
I'll try to make the plugin aware of this, meanwhile don't hide the sidebar manually before hiding it with the command :)
